# Generated by Django 4.2.30 on 2026-05-24 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Fuel & Procurement CSV'), ('UTILITY', 'Utility Portal Electricity CSV'), ('TRAVEL', 'Concur Corporate Travel CSV')], max_length=20)),
                ('row_count', models.IntegerField(default=0, help_text='Number of rows parsed and saved')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Diesel - UK DESNZ 2023', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion (Scope 1)'), ('ELECTRICITY', 'Electricity Consumption (Scope 2)'), ('FLIGHT', 'Business Flight (Scope 3)'), ('HOTEL', 'Hotel Accommodation (Scope 3)'), ('GROUND_TRANSPORT', 'Ground Transport (Scope 3)')], max_length=30)),
                ('factor_key', models.CharField(help_text='e.g. DIESEL, PETROL, FLIGHT_SHORT, FLIGHT_LONG', max_length=100, unique=True)),
                ('factor_value', models.DecimalField(decimal_places=6, help_text='kg CO2e per unit', max_digits=12)),
                ('unit', models.CharField(help_text='e.g. L, KG, M3, KWH, PKM, ROOM_NIGHT, KM', max_length=50)),
                ('source_reference', models.CharField(default='UK DESNZ 2023', help_text='Origin of the emission factor', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the client organization', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 (Direct Emissions)'), (2, 'Scope 2 (Indirect Emissions)'), (3, 'Scope 3 (Value Chain)')])),
                ('category', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('ELECTRICITY', 'Electricity Consumption'), ('FLIGHT', 'Business Flight'), ('HOTEL', 'Hotel Stay'), ('GROUND_TRANSPORT', 'Ground Transport')], max_length=30)),
                ('activity_value', models.DecimalField(decimal_places=4, help_text='Raw input activity quantity', max_digits=15)),
                ('activity_unit', models.CharField(help_text='Raw input unit (e.g. L, Gal, kWh, km)', max_length=50)),
                ('normalized_value_kwh', models.DecimalField(blank=True, decimal_places=4, help_text='Energy content in kWh (if applicable)', max_digits=15, null=True)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Calculated greenhouse gas emissions in kg CO2e', max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_row_number', models.IntegerField(blank=True, help_text='Line number in the original upload', null=True)),
                ('source_raw_json', models.JSONField(help_text='Full original raw row content from CSV')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Flagged for Investigation'), ('APPROVED', 'Approved by Analyst'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('flag_reason', models.TextField(blank=True, help_text='Explanation if flagged', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.datasource')),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='core.emissionfactor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(help_text='e.g. CREATE, UPDATE, APPROVE, FLAGGED, LOCK', max_length=20)),
                ('new_value', models.TextField(help_text='Description of values updated')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.emissionrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
