# Generated by Django 4.2.30 on 2026-05-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissionrecord',
            name='co2e_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Calculated greenhouse gas emissions in kg CO2e', max_digits=18, null=True),
        ),
    ]
